### ISSUE TITLE
RR object has no attribute off

### ISSUE THREAD

**Issue by ltfiend** [traffic-taffy/traffic-taffy#5]
Looks like this was added in the last edit of dpkt.py.

 File "/usr/local/lib/python3.11/site-packages/traffic_taffy/dissector_engine/dpkt.py", line 116, in dissect_dns
    self.incr(dissection, prefix + "an_off", record.off)
                                             ^^^^^^^^^^
AttributeError: 'RR' object has no attribute 'off'

**Comment by hardaker** [comment]
whoops!  Thanks for the bug report and fixed in 0.6.2, which I just pushed.
